Update dbms comapring models
prabudhall/placement_analysis pull request #13
Opened 2023-07-14 20:02 UTC by KRG17

updated all dbms and networking graphs and saved them

2023-07-17 17:23 UTC, prabudhall commented on compare_model/compare_graph/net_compare.csv
This file should be inside compare_model/compare_graph/networking . 
Do the needful changes in the code as well.

2023-07-17 17:24 UTC, prabudhall requested changes
Changes Requested

2023-07-17 17:26 UTC, prabudhall commented on compare_model/compare_graph/net_compare.csv
Or is it outside the subjects folder?

2023-07-17 17:29 UTC, prabudhall commented on compare_model/compare_graph/dbms_compare.csv
The file below this i.e. compare_model/compare_graph/net_compare.csv is having only 34 lines. So if you have updated the questions then please re run the code for networking and update the result for it as well

2023-07-17 17:29 UTC, prabudhall requested changes
Changes requested

2023-07-19 10:26 UTC, KRG17 commented on compare_model/compare_graph/dbms_compare.csv
Yes, i have updated teh net_comapre.csv file

2023-07-19 10:32 UTC, KRG17 commented on compare_model/compare_graph/net_compare.csv
Yes it is outside of the folder

2023-07-19 11:07 UTC, prabudhall approved these changes

2023-07-19 11:08 UTC, merged